import React, { useState, useEffect, useCallback } from 'react';
import { Keyboard, Play, RotateCcw, Trophy } from 'lucide-react';
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";


// 🎹 Virtual Keyboard Layout (with numbers, symbols, controls)
const keyboardLayout = [
  ["Esc", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12"],
  ["`", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "-", "=", "Backspace"],
  ["Tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "[", "]", "\\"],
  ["CAPS", "A", "S", "D", "F", "G", "H", "J", "K", "L", ";", "'", "Enter"],
  ["Shift", "Z", "X", "C", "V", "B", "N", "M", ",", ".", "/", "Shift"],
  ["Ctrl", "Fn", "Win", "Alt", " --  --  S p a c e. --  -- ", "Alt", "Menu", "Ctrl"]
];

// 🎵 Background Music (no toggle)
const BackgroundMusic = () => (
  <audio autoPlay loop>
    <source src="https://cdn.pixabay.com/download/audio/2022/03/15/audio_8e3a0b4e2a.mp3?filename=ambient-piano-112199.mp3" type="audio/mpeg" />
  </audio>
);

export function TypingTest() {
  const sampleTexts = [
    "The quick brown fox jumps over the lazy dog.",
    "Practice makes perfect when learning new skills.",
    "Technology continues to shape our future every day."
  ];

  const [currentText, setCurrentText] = useState(sampleTexts[0]);
  const [userInput, setUserInput] = useState('');
  const [startTime, setStartTime] = useState<number | null>(null);
  const [endTime, setEndTime] = useState<number | null>(null);
  const [isActive, setIsActive] = useState(false);
  const [errors, setErrors] = useState(0);
  const [activeKey, setActiveKey] = useState<string | null>(null);
  const [candidateName, setCandidateName] = useState("");

  // Track pressed keys for virtual keyboard
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => setActiveKey(e.key.length === 1 ? e.key.toUpperCase() : e.key);
    const handleKeyUp = () => setActiveKey(null);
    window.addEventListener("keydown", handleKeyDown);
    window.addEventListener("keyup", handleKeyUp);
    return () => {
      window.removeEventListener("keydown", handleKeyDown);
      window.removeEventListener("keyup", handleKeyUp);
    };
  }, []);

  const resetTest = useCallback(() => {
    setUserInput('');
    setStartTime(null);
    setEndTime(null);
    setIsActive(false);
    setErrors(0);
  }, []);

  const selectNewText = () => {
    const randomIndex = Math.floor(Math.random() * sampleTexts.length);
    setCurrentText(sampleTexts[randomIndex]);
    resetTest();
  };

  const startTest = () => {
    resetTest();
    setIsActive(true);
    setStartTime(Date.now());
  };

  const calculateStats = () => {
    if (!startTime || !endTime) return null;
    const timeInMinutes = (endTime - startTime) / 60000;
    const wordsTyped = userInput.trim().split(' ').length;
    const wpm = Math.round(wordsTyped / timeInMinutes);
    const accuracy = Math.round(((userInput.length - errors) / userInput.length) * 100);
    return { wpm, accuracy, errors, duration: timeInMinutes.toFixed(2) };
  };

  useEffect(() => {
    if (userInput.length === currentText.length && isActive) {
      setEndTime(Date.now());
      setIsActive(false);
    }
  }, [userInput, currentText, isActive]);

  const handleInputChange = (value: string) => {
    if (!isActive && value.length > 0) {
      setIsActive(true);
      setStartTime(Date.now());
    }
    setUserInput(value);

    let errorCount = 0;
    for (let i = 0; i < value.length; i++) {
      if (value[i] !== currentText[i]) {
        errorCount++;
      }
    }
    setErrors(errorCount);
  };

  const stats = calculateStats();
  const isCompleted = userInput.length === currentText.length;

  // 📜 Generate Certificate
const generateCertificate = (name: string, wpm: number, accuracy: number, errors: number) => {
  const doc = new jsPDF();

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("MultiTools Hub Certificate", 105, 30, { align: "center" });

  // Subtitle
  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.text(
    `This is to certify that ${name} has successfully completed the Typing Speed Test with the following results:`,
    20,
    50,
    { maxWidth: 170 }
  );

  // Results table after the text
  autoTable(doc, {
    startY: 70,
    head: [["WPM", "Accuracy", "Errors"]],
    body: [[wpm.toString(), `${accuracy}%`, errors.toString()]],
    styles: { halign: "center" },
    headStyles: { fillColor: [41, 128, 185] },
  });

  // Issue Date
  const issueDate = new Date().toLocaleDateString();
  doc.setFontSize(11);
  doc.text(`Issued on: ${issueDate}`, 20, doc.lastAutoTable.finalY + 15);

  // Footer at bottom
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(10);
  doc.text(
    "This certificate is auto-generated by MultiTools Hub based on the candidate's performance.",
    105,
    pageHeight - 20,
    { align: "center" }
  );
  doc.text("https://multitoolshub.com", 105, pageHeight - 12, { align: "center" });

  // Save file
  doc.save(`${name || "Candidate"}_Typing_Certificate.pdf`);
};

// 📥 Wrapper for button click
const downloadCertificate = () => {
  if (!stats || !candidateName) return;
  generateCertificate(candidateName, stats.wpm, stats.accuracy, stats.errors);
};
  return (
    <div className="max-w-5xl mx-auto px-6 py-10">
      <BackgroundMusic />
      
      {/* Header */}
      <div className="text-center mb-8">
        <div className="bg-orange-100 p-4 rounded-full w-fit mx-auto mb-4">
          <Keyboard className="h-10 w-10 text-orange-600" />
        </div>
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Typing Speed Test</h1>
        <p className="text-gray-600">Improve your typing with accuracy, speed, and fun!</p>
      </div>

      {/* Candidate Name */}
      <div className="mb-6 text-center">
        <input
          type="text"
          value={candidateName}
          onChange={(e) => setCandidateName(e.target.value)}
          placeholder="Enter your name for certificate"
          className="px-4 py-2 border rounded-lg w-80 text-center"
        />
      </div>

      {/* Controls */}
      <div className="flex gap-4 justify-center mb-8">
        <button onClick={startTest} className="px-6 py-3 bg-orange-600 text-white rounded-lg flex items-center gap-2">
          <Play size={18} /> Start Test
        </button>
        <button onClick={resetTest} className="px-6 py-3 bg-gray-600 text-white rounded-lg flex items-center gap-2">
          <RotateCcw size={18} /> Reset
        </button>
        <button onClick={selectNewText} className="px-6 py-3 border rounded-lg">New Text</button>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
        <div className="bg-white p-4 rounded-lg border text-center">
          <div className="text-2xl font-bold text-blue-600">{stats?.wpm || 0}</div>
          <div className="text-sm text-gray-600">WPM</div>
        </div>
        <div className="bg-white p-4 rounded-lg border text-center">
          <div className="text-2xl font-bold text-green-600">{stats?.accuracy || 100}%</div>
          <div className="text-sm text-gray-600">Accuracy</div>
        </div>
        <div className="bg-white p-4 rounded-lg border text-center">
          <div className="text-2xl font-bold text-red-600">{errors}</div>
          <div className="text-sm text-gray-600">Errors</div>
        </div>
        <div className="bg-white p-4 rounded-lg border text-center">
          <div className="text-2xl font-bold text-purple-600">
            {stats ? Math.round((userInput.length / currentText.length) * 100) : 0}%
          </div>
          <div className="text-sm text-gray-600">Progress</div>
        </div>
      </div>

      {/* Typing Text */}
      <div className="bg-white p-6 rounded-xl border mb-6">
        <p className="font-mono text-lg leading-relaxed mb-6">
          {currentText.split('').map((char, index) => (
            <span
              key={index}
              className={`px-1 py-0.5 rounded ${
                userInput[index]
                  ? userInput[index] === char
                    ? "bg-green-200 text-green-800"
                    : "bg-red-200 text-red-800"
                  : "text-gray-600"
              }`}
            >
              {char}
            </span>
          ))}
        </p>
        <textarea
          value={userInput}
          onChange={(e) => handleInputChange(e.target.value)}
          placeholder="Start typing here..."
          className="w-full h-32 p-4 border rounded-lg font-mono resize-none"
          disabled={isCompleted}
        />
      </div>

      {/* Virtual Keyboard */}
      <div className="bg-gray-100 p-4 rounded-lg mb-8">
        {keyboardLayout.map((row, i) => (
          <div key={i} className="flex justify-center mb-2">
            {row.map((key) => (
              <div
                key={key}
                className={`px-3 py-2 mx-1 rounded text-sm border shadow-sm ${
                  activeKey === key ? "bg-orange-500 text-white" : "bg-white"
                }`}
              >
                {key}
              </div>
            ))}
          </div>
        ))}
      </div>

      {/* Certificate Button */}
      {isCompleted && stats && (
        <div className="text-center">
          <Trophy className="h-12 w-12 text-yellow-500 mx-auto mb-4" />
          <h2 className="text-xl font-bold mb-4">Congratulations {candidateName || "Candidate"} 🎉</h2>
          <button onClick={downloadCertificate} className="px-6 py-3 bg-blue-600 text-white rounded-lg">
            Download Certificate (PDF)
          </button>
        </div>
      )}
    </div>
  );
}
